src/auth/app.js, src/auth/bin/www, src/auth/config.js, src/auth/package-lock.json, src/auth/package.json, src/auth/routes/index.js, src/auth/routes/users.js, src/statics/stylesheets/style.css, src/views/index.ejs, src/views/layout/head.ejs
index페이지만 띄어본 정말 기본 프로젝트 세팅입니다.
frontend 작업은 /src/views에서 작업할 예정입니다! :blush:
=> HM3: AUTH 서버 SETUP

src/spell/modules/mysql.js, src/spell/modules/redis.js, src/spell/routes/spell.js
/spell/:user_id GET - 유저 개인 오답 랭킹
기타 MySQL 쿼리에 Redis 추가
=> HM31: Add RedisCache / User Ranking Service 

src/chat/.gitignore, src/chat/app.js, src/chat/bin/www, src/chat/models/index.js, src/chat/models/room.js, src/chat/models/room_chats.js, src/chat/models/user.js, src/chat/module/handleDb.js, src/chat/module/spellCheck.js, src/chat/package-lock.json, src/chat/package.json, src/chat/routes/room.js, src/spell/.gitignore
데이터 베이스 연동했습니다 나머지 로직도 추가로 만들겟습니다. 먼저 이슈 #21 참고해서 config파일 추가해주세요
=> HM38 make new mysql database with sequelize

src/chat/.gitignore, src/chat/app.js, src/chat/bin/www, src/chat/model/chat.js, src/chat/models/index.js, src/chat/models/room.js, src/chat/models/room_chats.js, src/chat/models/user.js, src/chat/module/handleDb.js, src/chat/module/spellCheck.js, src/chat/package-lock.json, src/chat/package.json, src/chat/routes/room.js, src/spell/.gitignore
=> HM39 chat with mysql server

src/chat/module/handleDb.js, src/chat/module/socket.js, src/chat/module/spellCheck.js, src/chat/package-lock.json, src/chat/package.json, src/chat/routes/room.js
=> HM27 request to spell server

src/spell/app.js, src/spell/bin/www, src/spell/consumer.js, src/spell/modules/mysql.js, src/spell/modules/rabbitmq.js, src/spell/modules/spell-check.js, src/spell/package-lock.json, src/spell/package.json, src/spell/prod.js
일단 POST 방식은 유지하고
rabbitMQ로 처리할 수 있게끔만 추가했습니다
=> HM46: add rabbitMQ in spell

src/client/src/components/Profile.vue, src/client/src/components/SideBar.vue, src/client/src/components/chatting/RoomPage.vue
=> HM109: fix front errors

src/chat/module/handleDb.js, src/client/src/components/NavBar.vue, src/client/src/components/chatting/RoomListPage.vue, src/client/src/components/chatting/RoomPage.vue, src/client/src/store.js
일단 nav바에 알람 count할 변수를 store에 넣었습니당
room list도 store에 넣어서 관리하게 바꿨습니다
nav bar, roomlistpage, roompage 쪽 위주로 바꿨고
chat server에서 안 읽은 메세지 모든 방을 합친거를 같이 리턴하게 바꿨습니다
=> HM111: add_chat_alarm(1)

src/chat/bin/www, src/chat/module/socket.js, src/client/src/components/NavBar.vue, src/client/src/components/chatting/RoomListPage.vue
nav bar에 알람 소켓 추가
namespace : /alarm param:userid
알람(unread, friend req)는 store에 생성해서 관리하고 있습니다
=> HM111: add alarm socket

src/chat/bin/www, src/chat/module/handleDb.js, src/chat/module/socket.js, src/chat/routes/api_room.js, src/client/src/components/NavBar.vue, src/client/src/components/chatting/RoomPage.vue
소켓으로 chat alarm 변경하는 거까지 완성
메세지 보낼때만 변경하기 때문에 기존 사용하던 pubsub에 코드만 추가
아직 개별적인 알람 변경은 안하고 내일하겠습니당
=> HM111: add chat alarm

src/chat/module/socket.js, src/client/src/components/NavBar.vue, src/client/src/components/chatting/RoomPage.vue, src/client/src/store.js
소켓으로 각 방, 총 안 읽은 메세지 알람은 오는데 
이제 알람 받았을때 가장 최근 순서로 방 순서 변경(혹은 아예 업데이트 하던)
그리고 누가 방초대했을때 방 업데이트 되는 거 만들어야겠습니다
=> HM111: complete to chat alarm

src/chat/routes/api_room.js, src/client/src/components/chatting/RoomListPage.vue, src/client/src/components/chatting/RoomPage.vue
채팅 서버 -> 퇴장한 방이 마이룸일 경우 DB myroom = null
프론트 -> 친구 목록 store로 변경
기타 오류 수정
=> HM131: fix room out

src/chat/module/socket.js, src/chat/routes/api_room.js, src/client/src/components/NavBar.vue, src/client/src/components/chatting/RoomPage.vue
방 생성시 소켓통신으로 룸 업데이트하게 변경
socketIds 제거 Redis로 통합
=> HM131: fix make room

src/chat/module/socket.js, src/chat/routes/api_room.js, src/client/src/components/account/LoginPage.vue, src/client/src/components/friend/Friend.vue, src/client/src/store.js
알람소켓 join 예외처리 추가
updateFriend, Room 콜백으로 순차적으로 시도하게 변경
=> HM136: fix socket err

src/chat/routes/api_room.js
새 멤버 초대할때 lastet chat stime id를 마지막 chat으로 넣어서 
알림이 안울리게 변경
=> HM153: fix invite logic

src/chat/routes/api_room.js, src/client/src/components/NavBar.vue, src/client/src/components/Profile.vue, src/client/src/components/chatting/RoomListPage.vue, src/client/src/components/chatting/RoomPage.vue, src/client/src/components/friend/AddFriend.vue
초대 성공시 바로 members에 초대된 멤버들 추가
chat서버에서 res에 해당 stime 리턴 추가
소켓으로 메세지 알람 수신시 방 순서 맨 위로
showToast 메소드 추가
=> HM157: modify front invite

.gitignore, src/chat/module/handleDb.js, src/chat/module/socket.js, src/chat/routes/api_room.js, src/client/src/components/chatting/RoomListPage.vue, src/client/src/components/chatting/RoomPage.vue
=> HM147: change name with nickname

src/chat/module/handleDb.js
=> HM165: refactor readroom

src/chat/routes/api_room.js, src/client/src/components/chatting/RoomPage.vue
=> HM170: add friend chatroom error

src/chat/module/handleDb.js, src/chat/module/socket.js, src/chat/routes/api_room.js, src/client/src/components/NavBar.vue, src/client/src/components/chatting/RoomPage.vue, src/client/src/store.js
/out api를 소켓방식으로 변경해서 동시성 문제 해결
=> HM185: fix room delete

src/client/src/components/chatting/RoomPage.vue
=> HM197: socket init order handle

src/auth/modules/multer.js, src/auth/modules/multer_s3.js, src/auth/package-lock.json, src/auth/package.json, src/auth/routes/profile/profile.js, src/auth/routes/users.js, src/client/package-lock.json, src/client/src/components/EditProfile.vue, src/client/src/config.js, src/client/src/store.js
로컬에서 기존 디비 사용시 이미지 보이지 않을 수 있습니다! 
image_path를 이미지이름으로 업데이트 해주세요!
=> HM203: S3 and modify saving data for image_path
